# Generated by Django 4.2.7 on 2026-03-31 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_type', models.CharField(choices=[('faculty', 'Faculty'), ('subject', 'Subject'), ('section', 'Section')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('rows_imported', models.IntegerField(default=0)),
                ('errors', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
